Life.C doDamage changed
NoVariableGlobal/mood pull request #9
Opened 2020-04-09 17:35 UTC by Dankgard

2020-04-09 18:25 UTC, kyranet commented on src/LifeC.cpp
> +        return false;
```cpp
return currentLife <= 0;
```

2020-04-09 18:29 UTC, kyranet requested changes

2020-04-09 18:29 UTC, kyranet commented on src/LifeC.cpp
> +        return false;
```cpp
return currentLife <= 0;
```

2020-04-09 18:29 UTC, kyranet commented on src/LifeC.h
> +    // subtract the damage to the life (true if currentLife reaches 0)
```suggestion
    // Subtract the damage to the life. Returns a `boolean` value defining
    // whether or not `currentLife` reached 0.
```

2020-04-09 18:29 UTC, kyranet commented on src/MeleeEnemyBehaviourEC.cpp
> +                // TO DO: call sleep()
```suggestion
                // TODO(MiriamLeis): call `sleep()` when funcionality is available
```

2020-04-09 18:29 UTC, kyranet commented on src/BulletHurtPlayerEC.cpp
> +        // TO DO: call sleep() */
I'm pretty sure you want to call doDamage, and that you wanted to comment was the sleep not being available yet.
```suggestion
        // if player dies sleep method is called
        if (playerHealth->doDamage(damage))
            ;
        // TODO(MiriamLeis): call `sleep()` when funcionality is available
```

2020-04-09 20:23 UTC, kyranet requested changes

2020-04-09 20:23 UTC, kyranet commented on src/BulletHurtPlayerEC.cpp
> +        // TO DO: call sleep()
```suggestion
        // TODO(MiriamLeis): call `sleep()` when funcionality is available
```

2020-04-10 14:49 UTC, kyranet approved these changes

2020-04-16 10:32 UTC, pablojor approved these changes

2020-04-16 11:23 UTC, merged